export default {
  horizon: 'https://horizon.stellar.org',
  blocktrail: 'https://api.blocktrail.com/v1/BTC',
  bitpay: [
  'https://api.bitcore.io/api/BTC/mainnet',
    //'https://insight.bitpay.com/api',
    //'https://invoices.swaponline.site/proxybitpay',
  ],
  ghostscan: 'https://ghostscan.io/ghost-insight-api',
  nextscan: 'https://explore.next.exchange/#',
  nextExplorer: 'https://next.swaponline.io/mainnet',
  nextExplorerCustom: 'https://next.swaponline.io/mainnet',
  blockcypher: 'https://api.blockcypher.com/v1/btc/main',
  etherscan: 'https://api.etherscan.io/api',
  etherscanInvoices: 'https://invoices.swaponline.site/proxyetherscan',
  etherscan_ApiKey: 'RHHFPNMAZMD6I4ZWBZBF6FA11CMW9AXZNM',
  bscscan: 'https://api.bscscan.com/api',
  bscscan_ApiKey: 'WI4QEJSV19U3TF2H1DPQ2HR6712HW4MYKJ',
  maticscan: 'https://api.polygonscan.com/api',
  polygon_ApiKey: '8S2R45ZWG94HI7YK9RCXSK4VCASJ4XVA15',
  faucet: 'https://faucet.swaponline.site/mainnet/',
  btc2FAProtected: 'https://2fa.swaponline.site',
  btcPin: 'https://2fapin.swaponline.site',
  invoiceApi: 'https://invoices.swaponline.site',
  multisig: 'https://multisig.swaponline.site',
  txinfo: 'https://txinfo.swaponline.site',
  noxon: 'https://noxon.wpmix.net',
  etnxApi: 'https://pulse.electronero.org/api-etnx/api.php',
  etnxpApi: 'https://pulse.electronero.org/etnxp-api/api.php',
  etnxcApi: 'https://pulse.electronero.org/etnxc-api/api.php',
  ltnxApi: 'https://pulse.electronero.org/ltnx-api/api.php',
  gldxApi: 'https://pulse.electronero.org/gldx-api/api.php',
  crfiApi: 'https://passport.crystaleum.org/crfi-api/api.php',
  etnxTXExpl: 'blockexplorer.electronero.org/tx/',
  etnxpTXExpl: 'blockexplorer.electroneropulse.org/tx/',
  etnxcTXExpl: 'blockexplorer.electroneroclassic.org/tx/',
  ltnxTXExpl: 'blockexplorer.litenero.org/tx/',
  gldxTXExpl: 'blockexplorer.goldnero.org/tx/',
  crfiTXExpl: 'oracle.crystaleum.org/tx/',
  etnxBLOCKExpl: 'blockexplorer.electronero.org/block/',
  etnxpBLOCKExpl: 'blockexplorer.electroneropulse.org/block/',
  etnxcBLOCKExpl: 'blockexplorer.electroneroclassic.org/block/',
  ltnxBLOCKExpl: 'blockexplorer.litenero.org/block/',
  gldxBLOCKExpl: 'blockexplorer.goldnero.org/block/',
  crfiBLOCKExpl: 'oracle.crystaleum.org/block/',
}
